TIMEOUT=5
GRAPHICS=yes

:Carley Kernel
    PROTOCOL=limine
    KERNEL_PATH=boot:///kernel.elf
    MODULE_PATH=boot:///shell.elf
    MODULE_PATH=boot:///hello.elf
    MODULE_PATH=boot:///write.elf
    MODULE_PATH=boot:///edit.elf
    MODULE_PATH=boot:///gui.elf
