TIMEOUT=5
GRAPHICS=yes

:Carley OS
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/kernel.elf
    MODULE_PATH=boot:///boot/shell.elf
    MODULE_PATH=boot:///boot/input.elf
    MODULE_PATH=boot:///boot/hello.elf
    MODULE_PATH=boot:///boot/write.elf
    MODULE_PATH=boot:///boot/edit.elf
    MODULE_PATH=boot:///boot/gui.elf
    MODULE_PATH=boot:///boot/explorer.elf
    MODULE_PATH=boot:///boot/about.elf
    MODULE_PATH=boot:///boot/term.elf
    MODULE_PATH=boot:///boot/settings.elf
    MODULE_PATH=boot:///boot/shell_gui.elf
    MODULE_PATH=boot:///boot/monitor.elf
    MODULE_PATH=boot:///boot/calc_gui.elf
    MODULE_PATH=boot:///boot/libc.so
    MODULE_PATH=boot:///boot/demo.py
